# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a057130b74e46a42a0440381dbf53f26c47a9f3ff724234aea7f035e1622a5a128b145187de257b3b0545d5f6881fa7b02f5551d19565b98277fe4056ed0faaa

test:
  secret_key_base: 2640904cde8bbc790ffb3fdf86e5048b719b69c2f96dad3289585efd26501f01545ace386cead58b4981d1069ed875b8e7fcb811d270285a768fe5a9261cf76d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
